sequenceDiagram
actor User
User ->> FoodController : updateFood
activate FoodController
FoodController ->> FoodService : updateFood
activate FoodService
FoodService ->> FoodService : () -&gt;
activate FoodService
FoodService ->> FoodNotFoundException : new
activate FoodNotFoundException
FoodNotFoundException -->> FoodService : #32; 
deactivate FoodNotFoundException
FoodService -->> FoodService : #32; 
deactivate FoodService
FoodService ->> FoodMapper : mapSrcToDest
activate FoodMapper
FoodMapper -->> FoodService : #32; 
deactivate FoodMapper
FoodService ->> FoodMapper : toDTO
activate FoodMapper
FoodMapper ->> FoodResponseDTO : toString
activate FoodResponseDTO
FoodResponseDTO -->> FoodMapper : #32; 
deactivate FoodResponseDTO
FoodMapper -->> FoodService : #32; 
deactivate FoodMapper
FoodService -->> FoodController : #32; 
deactivate FoodService
deactivate FoodController
