-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cuisine
(
    id uuid NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL,
    CONSTRAINT cuisine_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.food
(
    id uuid NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    price double precision NOT NULL,
    restaurant_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    rating double precision,
    cuisine character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    image_key character varying(255) COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone,
    spice_level integer NOT NULL,
    CONSTRAINT food_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_budget_preference
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    budget character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone,
    CONSTRAINT user_budget_preference_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_cuisine_preference
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    cuisine_id uuid NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone,
    CONSTRAINT user_cuisine_preference_pkey PRIMARY KEY (id),
    CONSTRAINT uq_user_cuisine UNIQUE (user_id, cuisine_id)
);

CREATE TABLE IF NOT EXISTS public.user_food_preference
(
    status boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    food_id uuid NOT NULL,
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT user_food_preference_pkey PRIMARY KEY (id),
    CONSTRAINT uq_user_food UNIQUE (user_id, food_id)
);

CREATE TABLE IF NOT EXISTS public.user_spice_preference
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    spice_level integer NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id uuid NOT NULL,
    CONSTRAINT user_spice_preference_pkey PRIMARY KEY (id),
    CONSTRAINT uk3enk2ypdhq6bpyhwg96ak6r0h UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    city character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.user_budget_preference
    ADD CONSTRAINT fk_ubp_user FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_cuisine_preference
    ADD CONSTRAINT fk_ucp_cuisine FOREIGN KEY (cuisine_id)
    REFERENCES public.cuisine (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_cuisine_preference
    ADD CONSTRAINT fk_ucp_user FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_user_id
    ON public.user_cuisine_preference(user_id);


ALTER TABLE IF EXISTS public.user_food_preference
    ADD CONSTRAINT fk_ufp_food FOREIGN KEY (food_id)
    REFERENCES public.food (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_food_preference
    ADD CONSTRAINT fk_ufp_user FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_spice_preference
    ADD CONSTRAINT fk_usp_user FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS uk3enk2ypdhq6bpyhwg96ak6r0h
    ON public.user_spice_preference(user_id);

END;